In [9]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

data = pd.read_csv('https://raw.githubusercontent.com/koroteevmv/ML_course/refs/heads/main/ML4.1%20metrics/data/heart.csv')

y = data['output']
X = data.drop('output', axis=1)

X_train, X_test = X[:200], X[200:]
y_train, y_test = y[:200], y[200:]

logistic = LogisticRegression().fit(X_train, y_train)

print('Train 200, Test 103')
print('Train', logistic.score(X_train, y_train))
print('Test', logistic.score(X_test, y_test))
print()

N = int(X.shape[0] * 0.8)

X_train, y_train, X_test, y_test = X[:N], y[:N], X[N:], y[N:]

logistic = LogisticRegression().fit(X_train, y_train)

print('Train / Test 0.8')
print('Train', logistic.score(X_train, y_train))
print('Test', logistic.score(X_test, y_test))
print()

Train 200, Test 103
Train 0.9
Test 0.5436893203883495

Train / Test 0.8
Train 0.8884297520661157
Test 0.6229508196721312

C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [10]:
from numpy.random import shuffle
import numpy as np

mask = np.array([True] * N + [False] * (y.shape[0] - N))

shuffle(mask)

X_train, y_train, X_test, y_test = X[mask], y[mask], X[~mask], y[~mask]

logistic = LogisticRegression().fit(X_train, y_train)

print('Shuffle Train / Test 0.8')
print('Train', logistic.score(X_train, y_train))
print('Test', logistic.score(X_test, y_test))
print()

Shuffle Train / Test 0.8
Train 0.8760330578512396
Test 0.819672131147541

C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

logistic = LogisticRegression().fit(X_train, y_train)

print('Sklearn Train / Test 0.8')
print('Train', logistic.score(X_train, y_train))
print('Test', logistic.score(X_test, y_test))
print()

Sklearn Train / Test 0.8
Train 0.8636363636363636
Test 0.8852459016393442

C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [12]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

y_test_pred = logistic.predict(X_test)
y_train_pred = logistic.predict(X_train)

print(confusion_matrix(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

metrics = pd.DataFrame({
    "Train": [
        accuracy_score(y_train, y_train_pred),
        precision_score(y_train, y_train_pred),
        recall_score(y_train, y_train_pred),
        f1_score(y_train, y_train_pred),
    ],
    "Test": [
        accuracy_score(y_test, y_test_pred),
        precision_score(y_test, y_test_pred),
        recall_score(y_test, y_test_pred),
        f1_score(y_test, y_test_pred),
    ],
}, index = ["Accuracy", "Precision", "Recall", "F1"])

metrics

[[25  4]
 [ 3 29]]
              precision    recall  f1-score   support

           0       0.89      0.86      0.88        29
           1       0.88      0.91      0.89        32

    accuracy                           0.89        61
   macro avg       0.89      0.88      0.88        61
weighted avg       0.89      0.89      0.89        61

           Train   Test
Accuracy  0.8636 0.8852
Precision 0.8425 0.8788
Recall    0.9248 0.9062
F1        0.8817 0.8923

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier

models = {
    'Logistic Regression': LogisticRegression(random_state=42),
    'SVM': SVC(random_state=42),
    'KNN': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Gaussian Naive Bayes': GaussianNB(),
    'MLP': MLPClassifier(hidden_layer_sizes=(6, 6, 6), random_state=42)
}

results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    pre = precision_score(y_test, y_pred)
    recall =recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    results[name] = {
        'Accuracy': acc,
        'Precision': pre,
        'Recall': recall,
        'F1': f1,
    }

results = pd.DataFrame(results, index=["Accuracy", "Precision", "Recall", "F1"])

print(results)

C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

           Logistic Regression    SVM    KNN  Decision Tree  \
Accuracy                0.8852 0.7049 0.6885         0.7541
Precision               0.8788 0.6667 0.6857         0.8400
Recall                  0.9062 0.8750 0.7500         0.6562
F1                      0.8923 0.7568 0.7164         0.7368

           Gaussian Naive Bayes    MLP
Accuracy                 0.8689 0.5246
Precision                0.9000 0.5246
Recall                   0.8438 1.0000
F1                       0.8710 0.6882

In [14]:
from sklearn.datasets import load_iris

iris = load_iris()
data = pd.DataFrame(iris.data, columns=iris.feature_names)

X = data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

models = {
    'Logistic Regression': LogisticRegression(random_state=42),
    'SVM': SVC(random_state=42),
    'KNN': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Gaussian Naive Bayes': GaussianNB(),
    'MLP': MLPClassifier(hidden_layer_sizes=(6, 6, 6), random_state=42)
}

results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    pre = precision_score(y_test, y_pred, average='weighted')
    recall =recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    results[name] = {
        'Accuracy': acc,
        'Precision': pre,
        'Recall': recall,
        'F1': f1,
    }

results = pd.DataFrame(results, index=["Accuracy", "Precision", "Recall", "F1"])

results

C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

,Logistic Regression,SVM,KNN,Decision Tree,Gaussian Naive Bayes,MLP
Accuracy,1.0000,1.0000,1.0000,1.0000,1.0000,0.7667
Precision,1.0000,1.0000,1.0000,1.0000,1.0000,0.7806
Recall,1.0000,1.0000,1.0000,1.0000,1.0000,0.7667
F1,1.0000,1.0000,1.0000,1.0000,1.0000,0.7385

In [15]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_squared_log_error
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler

models = {
    'Linear Regression': LinearRegression(),
    'SVR': SVR(kernel='rbf', C=10),
    'Decision Tree': DecisionTreeRegressor(random_state=42, max_depth=5),
    'KNN': KNeighborsRegressor(n_neighbors=5),
    'MLP': MLPRegressor(
        hidden_layer_sizes=(50, 30),
        random_state=42,
        max_iter=1000,
        alpha=0.01
    )
}

data = pd.read_csv('https://raw.githubusercontent.com/koroteevmv/ML_course/refs/heads/main/ML3.1%20polynomial%20features/data/gen_regression.csv')

X = data[['x']]
y = data.y

scaler = StandardScaler()
# X = scaler.fit_transform(X)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    results[name] = {
        'MSE': mse,
        'RMSE': np.sqrt(mse),
        'MAE': mae,
        'R2': r2,
    }

pd.set_option('display.float_format', '{:.4f}'.format)
results = pd.DataFrame(results, index=["MSE", "RMSE", "MAE", "R2"])

results

C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

,Linear Regression,SVR,Decision Tree,KNN,MLP
MSE,571114439.5129,1058633459.7611,127748654.1575,108582229.8371,1772648430.1868
RMSE,23898.0007,32536.6479,11302.5950,10420.2797,42102.8316
MAE,17577.4152,18765.1052,9208.8968,9048.7473,31228.0921
R2,0.3082,-0.2824,0.8452,0.8685,-1.1474